### PR TITLE
Update for Rust version 1.0.0alpha

### PR DESCRIPTION
**Pull request by greencrab**
Make it compile against latest v1.0.0alpha.

### CODE REVIEW

**Comment by johannhof** [comment]
Hey, was this closed on purpose? Thanks for the contribution! Can I do something to help you get this completed? :)

**Comment by greencrab** [comment]
Hi, yeah after I did the pull request, I grab the latest rustc again and realize that while cargo build worked, cargo test failed.  I was going to work on it later, but didn't get a chance yet so closed the pull request.

Basically, this is the error I get for cargo test
assert_eq! ..."ERROR ^~~~~~~~~~~~ binary operation `==` cannot be applied to type: Scan"

I found something that might fix this, but won't have time to implement it until tonight.

http://stackoverflow.com/questions/25339603/how-to-test-for-equality-between-pointers-to-traits-in-rust

**Comment by johannhof** [comment]
That's fine, thanks for helping :)

**Comment by greencrab** [comment]
I update the code now it build and test correctly.  Pull request is ready.

**Comment by johannhof** [comment]
Awesome! Thanks! :heart:

**Pull request merged**
