### PR TITLE
Open access to token details. Closes #15.

### LINKED ISSUE #15: `tokenize` function is unusable due to private type
This should be disallowed by the compiler, but due to a bug it doesn't cause an error:
https://github.com/rust-lang/rust/issues/33216

It makes the `tokenize` function unusable because the `Block` enum can't be named, so it's impossible to do anything with the result.

### PR DESCRIPTION
**Pull request by vi**

### CODE REVIEW

**Comment by lucab** [comment]
Ping @johannhof. It looks like rustup is stuck with a private fork of markdown due to this.

**Comment by johannhof** [comment]
Hey there, wow, I wasn't aware rustup (or anyone else with serious intentions) was using this. This library lacks support for several much-used markdown features, though completing this has been on my list for a long time.

@vi thanks for the patches. I'll give you commit rights in case you want to tinker some more with this.

**Comment by lucab** [comment]
@johannhof thanks for the very quick reaction! I ended up here following the reason behind the only [rustup git dependency](https://github.com/rust-lang-nursery/rustup.rs/blob/1.0.0/Cargo.toml#L52). It woule be nice to have a new markdown-rs version tagged and uploaded to crates.io to get rid of that.

**Comment by johannhof** [comment]
@lucab done :)

**Comment by lucab** [comment]
Thanks, and a rust-y 2017 to you: https://github.com/rust-lang-nursery/rustup.rs/pull/896 :tada:

**Pull request merged**
